# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-29 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('bborrow', models.IntegerField()),
            ],
            options={
                'db_table': 't_book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBookrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brname', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 't_bookrack',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBooktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bttype', models.CharField(max_length=20)),
                ('btday', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_booktype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bborrowtime', models.DateTimeField()),
                ('breturntime', models.DateTimeField()),
                ('brealreturntime', models.DateTimeField(blank=True, null=True)),
                ('badd', models.IntegerField()),
                ('breturn', models.IntegerField()),
            ],
            options={
                'db_table': 't_borrow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='THouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_house',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lname', models.CharField(max_length=20)),
                ('lusername', models.CharField(max_length=20)),
                ('ltel', models.CharField(max_length=20)),
                ('lsite', models.CharField(max_length=50)),
                ('lemail', models.CharField(max_length=20)),
                ('lnet', models.CharField(max_length=50)),
                ('lbirthday', models.CharField(max_length=20)),
                ('lword', models.CharField(max_length=100)),
                ('lmoney', models.CharField(max_length=20)),
                ('ltime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_library',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20)),
                ('rcardtype', models.CharField(max_length=20)),
                ('rcardnum', models.CharField(max_length=20)),
                ('rtel', models.CharField(max_length=20)),
                ('remail', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_reader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TReadertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rttype', models.CharField(max_length=20)),
                ('rtnum', models.IntegerField()),
            ],
            options={
                'db_table': 't_readertype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=20)),
                ('rborrow', models.IntegerField()),
                ('rsys', models.IntegerField()),
                ('rreader', models.IntegerField()),
                ('rbook', models.IntegerField()),
                ('rinquiry', models.IntegerField()),
                ('rpwd', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 't_root',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TWriter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_writer',
                'managed': False,
            },
        ),
    ]
